# Generated by Django 5.2.1 on 2025-05-30 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PathAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(default=dict)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FunnelAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict)),
                ('is_processed', models.BooleanField(default=False)),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analytics.funnel')),
            ],
        ),
        migrations.CreateModel(
            name='FunnelStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url_pattern', models.CharField(max_length=255)),
                ('step_order', models.IntegerField()),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='analytics.funnel')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='Heatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url_pattern', models.CharField(max_length=255)),
                ('heatmap_type', models.CharField(choices=[('click', 'Click Heatmap'), ('move', 'Movement Heatmap')], max_length=10)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(default=dict)),
                ('resolution_width', models.IntegerField(default=1920)),
                ('resolution_height', models.IntegerField(default=1080)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['url_pattern'], name='analytics_h_url_pat_72d3ac_idx'), models.Index(fields=['heatmap_type'], name='analytics_h_heatmap_be1bbe_idx'), models.Index(fields=['date_from', 'date_to'], name='analytics_h_date_fr_f16ad6_idx')],
            },
        ),
    ]
