# Generated by Django 5.2.1 on 2025-05-30 07:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_agent', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('referrer', models.URLField(blank=True, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('mouse_move', 'Mouse Move'), ('mouse_click', 'Mouse Click'), ('scroll', 'Scroll'), ('form_input', 'Form Input'), ('page_view', 'Page View'), ('custom', 'Custom Event')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('url', models.URLField()),
                ('data', models.JSONField(default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracking.session')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'event_type'], name='tracking_ev_session_0c1997_idx'), models.Index(fields=['event_type', 'timestamp'], name='tracking_ev_event_t_648ab0_idx'), models.Index(fields=['url'], name='tracking_ev_url_b68fd2_idx')],
            },
        ),
    ]
