version: '3.8'

services:
  backend:
    build: ./backend
    container_name: mouse-tracker-backend
    restart: always
    volumes:
      - ./backend:/app
      - backend_static:/app/static
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - MONGODB_URI=mongodb://mongo:27017/mouse_tracker
      - REDIS_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,frontend
    depends_on:
      - mongo
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/tracking/test/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  frontend:
    build: ./frontend
    container_name: mouse-tracker-frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy

  mongo:
    image: mongo:6
    container_name: mouse-tracker-mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    command: mongod --bind_ip_all
    environment:
      - MONGO_INITDB_DATABASE=mouse_tracker

  redis:
    image: redis:7-alpine
    container_name: mouse-tracker-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
  backend_static: 