version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mouse-tracker-frontend
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://backend-nginx:80/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mouse-tracker-network
    depends_on:
      backend:
        condition: service_healthy

  frontend-nginx:
    build:
      context: ./frontend/nginx
      dockerfile: Dockerfile
    container_name: mouse-tracker-frontend-nginx
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - frontend
    networks:
      - mouse-tracker-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mouse-tracker-backend
    restart: always
    environment:
      - DEBUG=1
      - SECRET_KEY=your-secret-key-here
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1] backend backend-nginx frontend frontend-nginx
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8000,http://localhost,http://frontend-nginx:80
      - MONGODB_URI=mongodb://mongodb:27017/
      - MONGODB_DB=mouse_tracker
    volumes:
      - ./backend:/app
      - backend_static:/app/staticfiles
      - backend_media:/app/media
    networks:
      - mouse-tracker-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/tracking/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend-nginx:
    build:
      context: ./backend/nginx
      dockerfile: Dockerfile
    container_name: mouse-tracker-backend-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - backend_static:/app/staticfiles:ro
      - backend_media:/app/media:ro
    depends_on:
      - backend
    networks:
      - mouse-tracker-network

  mongodb:
    image: mongo:latest
    container_name: mouse-tracker-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mouse-tracker-network

networks:
  mouse-tracker-network:
    driver: bridge

volumes:
  mongodb_data:
  backend_static:
  backend_media: 